name: data
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
      - ./scripts/github-commits.js
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://api.github.com/users/cspray/events/public
          downloaded_filename: github_commits.json
          postprocess: ./scripts/github-commits.js
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://api.stackexchange.com/2.2/me/answers?order=desc&sort=votes&site=stackoverflow&filter=!nL_HTxB8XR&key=d2rqIgQGMSkvdyKwZ6PaSw((&access_token=${{
            secrets.STACKOVERFLOW_API_TOKEN  }}
          downloaded_filename: stackoverflow_answers.json
